config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :activities
  end
  root 'places#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :place
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "posts" table
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @place = Place.find(params[:place_id])
    @activity = @place.activities.new
  end

  def create
    @place = Place.find(params[:place_id])
    @activity = @place.activities.new(activity_params)
    if @activity.save
      redirect_to @place, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :date_posted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @activities = @place.activities
  end

  def new
    @place = Place.new
    @activity = @place.activities.build
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to @place, notice: 'Place was successfully created.'
    else
      render :new
    end
  end

  # def update
  #   @place = Place.find(params[:id])
  #   if @place.update(place_params)
  #     redirect_to @place, notice: 'Place was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end

  private

  def place_params
    params.require(:place).permit(:name, activities_attributes: [:name, :description, :date_posted])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: [@place, @activity], local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date_posted %>
    <%= form.date_field :date_posted %>
  </div>

  <%= form.submit %>
<% end %>

app/views/activities/new.html.erb
<h1>Create New Activity for <%= @place.name %></h1>

<%= render 'form', place: @place, activity: @activity %>

<%= link_to 'Back', place_path(@place) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- Add more fields as needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/index.html.erb
<h1>Places I've been</h1>
<ul>
  <% @places.each do |place| %>
    <li><%= link_to place.name, place_path(place) %></li>
  <% end %>
</ul>

<%= link_to 'Add a New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<% if @activities.any? %>
  <h2>Post(s):</h2>
  <ul>
    <% @activities.each do |activity| %>
      <li>
        <strong><%= activity.name %></strong><br>
        <%= activity.description %><br>
        Date Posted: <%= activity.date_posted %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No post found for this place.</p>
<% end %>

<%= link_to 'New Post', new_place_activity_path(@place) %> </p>

<%= link_to 'Back', places_path %>